//
// Created by Komatta on 2016-03-11.
//

#ifndef ADAPTIVEHUFFMANCODING_CORE_H_IN_H
#define ADAPTIVEHUFFMANCODING_CORE_H_IN_H

#define CORE_VERSION "0.0.1"

#endif //ADAPTIVEHUFFMANCODING_CORE_H_IN_H
